# This is a basic workflow to help you get started with Actions

name: Download And Cache Livestream VOD

concurrency: streamdownloader
# Controls when the workflow will run
on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Cache For Downloaded Livestream
        uses: actions/cache@v3.0.8
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: "*.mp4"
          # An explicit key for restoring and saving the cache
          key: stream-vod

      # Runs a set of commands using the runners shell
      - name: Download livestream
        continue-on-error: true
        run: yt-dlp https://www.youtube.com/channel/UC-5k8MpdvixOEQWTpkxH4LQ/live --live-from-start
